### ISSUE TITLE
Allow values for named keys to be kept

### ISSUE THREAD

**Issue by joshdunnlime** [hija/clean-dotenv#5]
A simple example explains this best.

**.env**
```
password=pa55w0rd
url=www.google.com
```

with a command similar to:

```bash
dotenv-clean --keep url
```

the output would look as follows:

**.env.example**
```
password=
url=www.google.com
```

**Comment by joshdunnlime** [comment]
Lovely package btw!

**Comment by hija** [comment]
Implemented :)

Please test and feel free to open a new issue if the feature does not work as intended.

**Comment by joshdunnlime** [comment]
@hija it works exactly as expected. Thanks for the rapid update! :)
